Fix roundtrip-test to use new "sweetener" filename.

diff --git a/roundtrip-test b/roundtrip-test
--- a/roundtrip-test
+++ b/roundtrip-test
@@ -10,14 +10,18 @@
 # 2. Convert to sweet, then convert back to S-expressions (placing it in ,2)
 # They should be the same.  This puts stress on both converters.
 
-TESTFILE="${1:-iformat.scm}"
+TESTFILE="${1:-sweetener.scm}"
 
-make iformat.scm
+if [ ! -f "$TESTFILE" ]
+then
+  echo "Failure: File $TESTFILE does not exist."
+  exit 1
+fi
 
 ./pprint < "$TESTFILE" > ,1
 
-guile iformat.scm < "$TESTFILE" > ,2reformat
-./sweet-filter < ,2reformat | ./pprint > ,2
+./sweetener < "$TESTFILE" > ,2-sweetened
+./sweet-filter < ,2-sweetened | ./pprint > ,2
 
 echo "DIFFERENCES (should be none):"
 echo
