Improve diff-s-sweet
  - Add multiple options, and allow "-w" to support a list of files

diff --git a/src/diff-s-sweet b/src/diff-s-sweet
--- a/src/diff-s-sweet
+++ b/src/diff-s-sweet
@@ -1,65 +1,68 @@
 #!/bin/sh
 
-# diff-s-sweet: Given two filenames
-# (in s-expressions and sweet-expressions respectively),
-# show the semantic differences between them.
+# diff-s-sweet: Show differences between s-expressions and sweet-expressions
 # If there's a difference, show the difference and return an error code,
 # else show nothing and return true (0).
-# When given "-w" ("well-formatted"), check if it's well-formatted
-# by running "unsweeten" and seeing if there's a semantic difference.
 
 # (C) 2013 David A. Wheeler
 # Released under the MIT license
 
-# TODO: Add support for:
 # -w Check if file list is set of well-formatted s-expressions
 #    (if no files, stdin; support - as stdin)
-# Document usage, etc. in man page
+# -l don't show differences, just list s-expression filenames with differences
 
+# Set up the defaults.
 export PATH="@PATH_PREFIX@$PATH"
 SWEETEN="sweeten"
 UNSWEETEN="unsweeten"
-
 well_formatted=0
+list_filenames=0
+unified=10
+invoke_error=99
+keep_temp=0
+
+
+# Process options.
+# The POSIX standard has "getopts" to nicely parse utility options. Sadly,
+# it only portably handles short option names. (You can use "-:" to sort-of
+# get long names, but it's a rather ugly hack.)  It'll do for us.
+
+GETOPTS="hklwU:"
+
+usage() {
+  echo "Usage:"
+  echo "  $0 [-l | -U n] [-k] s-expression-filename sweet-expression-filename"
+  echo "  $0 -w [-l | -U n] [-k] s-expression-filename*"
+  exit $invoke_error
+}
 
 if [ $# -eq 0 ] ; then
-  echo "Usage: $0 s-expression-filename sweet-expression-filename"
-  echo "       $0 -w s-expression-filename"
-  exit 99
+  usage
+elif [ "$1" == "--help" ] ; then
+  usage
 fi
 
-if [ "$1" = "-w" ] ; then
-  well_formatted=1
-  shift
-fi
-
-if [ "$well_formatted" -eq 0 ] ; then
-  if [ $# -ne 2 ] ; then
-    echo "Must have 2 filenames"
-    exit 98
-  fi
-  if [ ! -f "$1" ] ; then
-    echo "File 1 (for s-expressions) must exist as a normal file"
-    exit 98
-  fi
-  if [ ! -f "$2" ] ; then
-    echo "File 2 (for sweet-expressions) must exist as a normal file"
-    exit 98
-  fi
-else
-  if [ $# -ne 1 ] ; then
-    echo "Must have 1 filename"
-    exit 98
-  fi
-  if [ ! -f "$1" ] ; then
-    echo "File 1 (for s-expressions) must exist as a normal file"
-    exit 98
-  fi
-fi
+while getopts "$GETOPTS" optchar ; do
+  case "$optchar" in
+    h) usage ;;
+    k) keep_temp=1 ;;
+    l) list_filenames=1 ;;
+    w) well_formatted=1 ;;
+    U) unified="$OPTARG" ;;  # Presume it's an integer.
+    \?) usage ;;
+    *) echo "Unimplemented option" ; usage ;;  # "Can't" happen
+  esac
+done
+shift $(($OPTIND - 1))
 
 
-# Pretty print filter, from stdin to stdout.
+
+# Define functions to do the main work
+
+
+# This is a Scheme s-expression pretty print filter (from stdin to stdout)
 prettyprint() {
+sed -e 's/^#lang  *[-a-zA-Z0-9]*//' |   # Remove Racket-specific extension
 guile -c '
   (use-modules (ice-9 pretty-print))
    (do ((x (read) (read)))
@@ -67,19 +70,99 @@ guile -c '
    (pretty-print x))'
 }
 
-# The sed commands deletes ;-only lines; the awk command
-# merges 2+ blank lines into one blank line.
-# We don't ignore ALL blank lines, because blank lines can have an effect.
-# For example, a blank line followed by an indent has
-# a different meaning if we remove the blank line.
-# All of this assumes that we're not using multi-line strings.
 
-prettyprint < "$1" > ,first
+# Report comparison of s-expression file "$1" with either
+# "$2" (if no -w) or an unsweetened "$1" (if there is a -w).
+# Handle input file "-" specially in $1.
 
-if [ "$well_formatted" -eq 0 ] ; then
-  ${UNSWEETEN} "$2" | prettyprint > ,second
+report_comparison() {
+
+  # Determine "s_expr", which contains the name of the s-expression file.
+  oldname="$1"
+  if [ "$oldname" = "-" ] ; then
+    s_expr="$(mktemp)"
+    cat > "$s_expr"
+  else
+    s_expr="$oldname"
+    if [ ! -f "$s_expr" ] ; then
+      echo "Not an existing normal file: $s_expr"
+      exit $invoke_error
+    fi
+  fi
+
+  # Create formatted s-expression and t-expression files to compare
+  fmt_s="$(mktemp)"  # formatted s-expression file
+  fmt_t="$(mktemp)"  # formatted t-expression file
+  if [ "$keep_temp" -eq 1 ] ; then
+    echo "S-expr file '$oldname' to be formatted into $fmt_s"
+    echo "T-expr file to be formatted into $fmt_t"
+    echo
+  fi
+
+  prettyprint < "$s_expr" >> "$fmt_s"
+  if [ "$well_formatted" -eq 1 ] ; then # We have "-w"
+    ${UNSWEETEN} < "$s_expr" | prettyprint >> "$fmt_t"
+    newname="$1.sscm"
+  else
+    if [ ! -f "$2" ] ; then
+      echo "Not an existing normal file (as a t-expression file): $2"
+      exit $invoke_error
+    fi
+    ${UNSWEETEN} < "$2" | prettyprint >> "$fmt_t"
+    newname="$2"
+  fi
+
+  # Always print the filenames on a difference, then optionally the details.
+  # We do it this way because diff only reports the irrelevant *temporary*
+  # filenames unless we use the nonportable GNU extension "--label"
+  if cmp -s -- "$fmt_s" "$fmt_t" ; then
+    returnvalue=0
+  else
+    if [ "$list_filenames" -eq 1 ] ; then
+      printf "%s\n" "$oldname"
+    else
+      # Print filenames specially because we compare temporary files instead:
+      printf -- "--- %s\n" "$oldname"
+      printf -- "+++ %s\n" "$newname"
+      diff -U "$unified" -- "$fmt_s" "$fmt_t" | tail -n +3
+      echo
+    fi
+    returnvalue=1
+  fi
+
+  # Remove temporary files
+  if ! [ "$keep_temp" -eq 1 ] ; then
+    rm -f -- "$fmt_s" "$fmt_t"
+    if [ "$1" = "-" ] ; then
+      rm -f -- "$s_expr" # Remove specially-created file
+    fi
+  fi
+  return $returnvalue
+}
+
+
+# Do the work! This is the top level that invokes the rest.
+
+exit_value=0
+if [ "$well_formatted" -eq 1 ] ; then
+  if [ $# -eq 0 ] ; then
+    report_comparison "-"
+    exit_value=$?
+  else
+    for file ; do
+      if ! report_comparison "$file" ; then
+        exit_value=$(($exit_value + 1))
+      fi
+    done
+  fi
 else
-  ${UNSWEETEN} "$1" | prettyprint > ,second
+  if [ $# -ne 2 ] ; then
+    echo "Must have 2 filenames"
+    exit $invoke_error
+  fi
+  report_comparison "$1" "$2"
+  exit_value=$?
 fi
 
-diff -u ,first ,second
+exit $exit_value
+
